---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# xisoband

<!-- badges: start -->
<!-- badges: end -->

The goal of xisoband is to make isoband a bit more generally useable. 


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(xisoband)
e <- whatarelief::elevation()
plot(iso <- xisoband::xisobands(e, extent = c(-180, 180, -90, 90)))
maps::map(add = TRUE, col = "firebrick", fill = FALSE)

ximage::ximage(e, extent = c(-180, 180, -90, 90))
plot(iso, add = TRUE)

```


## Code of Conduct
  
Please note that the xisoband project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/1/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.
